### ISSUE TITLE
Dockerfile configuration

### ISSUE THREAD

**Issue by jb2martel** [kwonoj/docker-arch-emscripten#32]
The dockerfile doesn't contain default values for target and protobuf and emscripten library versions.
This info could be added in the README or set by default in the dockerfile to help beginners out.
Values that work:
ARG BUILD_TARGET="protobuf"
ARG PROTOBUF_VERSION="3.6.1"
ARG EMSCRIPTEN_VERSION="1.38.32-1"

**Comment by kwonoj** [comment]
Could be, just prefer explicit and I use this as base image in most case so didn't care a lot. Except `BUILD_TARGET` (I'd expect non-protobuf by default), feel free to open PR if needed.
